--------------------------------------------------------
--  File created - Wednesday-February-26-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CERT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DEMO_CA"."CERT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 281 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CHANNEL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DEMO_CA"."CHANNEL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CUSTOMER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DEMO_CA"."CUSTOMER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence DOCUMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DEMO_CA"."DOCUMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 381 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ERROR_CODE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DEMO_CA"."ERROR_CODE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence FUNCTION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DEMO_CA"."FUNCTION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence OBJECT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DEMO_CA"."OBJECT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence OCSP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DEMO_CA"."OCSP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ROLE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DEMO_CA"."ROLE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SERVER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DEMO_CA"."SERVER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SIGNATURE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DEMO_CA"."SIGNATURE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 481 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SIGNER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DEMO_CA"."SIGNER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 221 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence TRANS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DEMO_CA"."TRANS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 701 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence TRUSTED_CA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DEMO_CA"."TRUSTED_CA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence USER_SYS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DEMO_CA"."USER_SYS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table CERT
--------------------------------------------------------

  CREATE TABLE "DEMO_CA"."CERT" 
   (	"ID" NUMBER(19,0), 
	"SIGNER_ID" NUMBER(19,0), 
	"SERIAL" VARCHAR2(255 BYTE), 
	"NAME" VARCHAR2(255 BYTE), 
	"DN" VARCHAR2(255 BYTE), 
	"UID_CERT" VARCHAR2(255 BYTE), 
	"ISSUER" VARCHAR2(255 BYTE), 
	"ISSUER_ID" NUMBER(19,0), 
	"OCSP_ID" NUMBER(19,0), 
	"VALIDFR" TIMESTAMP (0), 
	"VALIDTO" TIMESTAMP (0), 
	"KEYLENGTH" NUMBER(10,0), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"BASE64" VARCHAR2(4000 BYTE), 
	"ALIAS" VARCHAR2(255 BYTE), 
	"STATUS" NUMBER(10,0), 
	"CREATE_DATE" TIMESTAMP (0) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFY_DATE" TIMESTAMP (0), 
	"METADATA" CLOB, 
	"STATUS_CERT" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("METADATA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table CHANNEL
--------------------------------------------------------

  CREATE TABLE "DEMO_CA"."CHANNEL" 
   (	"ID" NUMBER(19,0), 
	"CHANNEL_CODE" VARCHAR2(255 BYTE), 
	"STATUS" NUMBER(10,0), 
	"CREATE_DATE" TIMESTAMP (0) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFY_DATE" TIMESTAMP (0), 
	"METADATA" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("METADATA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "DEMO_CA"."CUSTOMER" 
   (	"ID" NUMBER(19,0), 
	"CIF" VARCHAR2(255 BYTE), 
	"STATUS" NUMBER(10,0), 
	"CREATE_DATE" TIMESTAMP (0) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFY_DATE" TIMESTAMP (0), 
	"METADATA" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("METADATA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table DOCUMENT
--------------------------------------------------------

  CREATE TABLE "DEMO_CA"."DOCUMENT" 
   (	"ID" NUMBER(19,0), 
	"TRANS_ID" NUMBER(19,0), 
	"TYPE" NUMBER(10,0), 
	"FOLDER_SAVE" VARCHAR2(1000 BYTE), 
	"SIZE_DOC" NUMBER(10,0), 
	"STATUS" NUMBER(10,0), 
	"CREATE_DATE" TIMESTAMP (0) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFY_DATE" TIMESTAMP (0), 
	"METADATA" CLOB, 
	"NAME_ORI" VARCHAR2(200 BYTE), 
	"NAME_SAVE" VARCHAR2(200 BYTE), 
	"ERROR_CODE_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("METADATA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ERROR_CODE
--------------------------------------------------------

  CREATE TABLE "DEMO_CA"."ERROR_CODE" 
   (	"ID" NUMBER(19,0), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"CREATE_DATE" TIMESTAMP (0) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFY_DATE" TIMESTAMP (0), 
	"METADATA" CLOB, 
	"STATUS" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("METADATA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table FUNCTION
--------------------------------------------------------

  CREATE TABLE "DEMO_CA"."FUNCTION" 
   (	"ID" NUMBER(19,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"ACTION" VARCHAR2(255 BYTE), 
	"OBJECT_ID" NUMBER(19,0), 
	"CREATER_ID" NUMBER(19,0), 
	"CREATE_DATE" TIMESTAMP (0) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFY_DATE" TIMESTAMP (0), 
	"METADATA" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("METADATA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table OBJECT
--------------------------------------------------------

  CREATE TABLE "DEMO_CA"."OBJECT" 
   (	"ID" NUMBER(19,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"HREF" VARCHAR2(255 BYTE), 
	"PARENT_ID" NUMBER(10,0), 
	"CREATER_ID" NUMBER(19,0), 
	"CREATE_DATE" TIMESTAMP (0) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFY_DATE" TIMESTAMP (0), 
	"METADATA" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("METADATA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table OCSP
--------------------------------------------------------

  CREATE TABLE "DEMO_CA"."OCSP" 
   (	"ID" NUMBER(19,0), 
	"URL" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"HAS_CONNECT" CHAR(1 BYTE), 
	"STATUS" NUMBER(10,0), 
	"CREATER_ID" NUMBER(19,0), 
	"CREATE_DATE" TIMESTAMP (0) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFY_DATE" TIMESTAMP (0), 
	"METADATA" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("METADATA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ROLE
--------------------------------------------------------

  CREATE TABLE "DEMO_CA"."ROLE" 
   (	"ID" NUMBER(19,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"CREATER_ID" NUMBER(19,0), 
	"CREATE_DATE" TIMESTAMP (0) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFY_DATE" TIMESTAMP (0), 
	"METADATA" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("METADATA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table ROLE_FUNCTION_MAP
--------------------------------------------------------

  CREATE TABLE "DEMO_CA"."ROLE_FUNCTION_MAP" 
   (	"ROLE_ID" NUMBER(19,0), 
	"FUNCTION_ID" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SERVER
--------------------------------------------------------

  CREATE TABLE "DEMO_CA"."SERVER" 
   (	"ID" NUMBER(19,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"IP" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"STATUS" NUMBER(10,0), 
	"CREATE_DATE" TIMESTAMP (0) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFY_DATE" TIMESTAMP (0), 
	"METADATA" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("METADATA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table SIGNATURE
--------------------------------------------------------

  CREATE TABLE "DEMO_CA"."SIGNATURE" 
   (	"ID" NUMBER(19,0), 
	"DOCUMENT_ID" NUMBER(19,0), 
	"CERT_ID" NUMBER(19,0), 
	"TYPE" NUMBER(10,0), 
	"STATUS" NUMBER(10,0), 
	"CREATE_DATE" TIMESTAMP (0) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFY_DATE" TIMESTAMP (0), 
	"METADATA" CLOB, 
	"SIGN_DATE" TIMESTAMP (0), 
	"ERROR_CODE_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("METADATA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table SIGNER
--------------------------------------------------------

  CREATE TABLE "DEMO_CA"."SIGNER" 
   (	"ID" NUMBER(19,0), 
	"CUSTOMER_ID" NUMBER(19,0), 
	"USERNAME" VARCHAR2(255 BYTE), 
	"STATUS" NUMBER(10,0), 
	"CREATE_DATE" TIMESTAMP (0) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFY_DATE" TIMESTAMP (0), 
	"METADATA" CLOB, 
	"CHANNEL_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("METADATA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TRANS
--------------------------------------------------------

  CREATE TABLE "DEMO_CA"."TRANS" 
   (	"ID" NUMBER(19,0), 
	"TRANS_REF_ID" VARCHAR2(255 BYTE), 
	"TRANS_REF_TYPE" NUMBER(10,0), 
	"SIGNER_ID" NUMBER(19,0), 
	"TYPE_ACTION" NUMBER(10,0), 
	"TYPE_HAS_SIGNATURE" CHAR(1 BYTE), 
	"STATUS" NUMBER(10,0), 
	"CREATE_DATE" TIMESTAMP (0) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFY_DATE" TIMESTAMP (0), 
	"METADATA" CLOB, 
	"SERVER_ID" NUMBER(19,0), 
	"CERT_ID" NUMBER(19,0), 
	"ERROR_CODE_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("METADATA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TRUSTED_CA
--------------------------------------------------------

  CREATE TABLE "DEMO_CA"."TRUSTED_CA" 
   (	"ID" NUMBER(19,0), 
	"SERIAL" VARCHAR2(255 BYTE), 
	"NAME" VARCHAR2(255 BYTE), 
	"DN" VARCHAR2(1000 BYTE), 
	"UID_CERT" VARCHAR2(255 BYTE), 
	"ISSUER" VARCHAR2(1000 BYTE), 
	"ISSUER_ID" NUMBER(19,0), 
	"VALIDFR" TIMESTAMP (0), 
	"VALIDTO" TIMESTAMP (0), 
	"KEYLENGTH" NUMBER(10,0), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"BASE64" CLOB, 
	"ALIAS" VARCHAR2(255 BYTE), 
	"STATUS" NUMBER(10,0), 
	"CREATER_ID" NUMBER(19,0), 
	"CREATE_DATE" TIMESTAMP (0) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFY_DATE" TIMESTAMP (0), 
	"METADATA" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("BASE64") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("METADATA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TRUSTED_CA_OCSP_MAP
--------------------------------------------------------

  CREATE TABLE "DEMO_CA"."TRUSTED_CA_OCSP_MAP" 
   (	"TRUSTED_CA_ID" NUMBER(19,0), 
	"OCSP_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_SYS
--------------------------------------------------------

  CREATE TABLE "DEMO_CA"."USER_SYS" 
   (	"ID" NUMBER(19,0), 
	"USERNAME" VARCHAR2(255 BYTE), 
	"NAME" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"STATUS" NUMBER(10,0), 
	"COUNT_LOGIN_FAIL" NUMBER(10,0), 
	"LOGIN_SUCCESS_DATE" TIMESTAMP (0), 
	"CREATER_ID" NUMBER(19,0), 
	"CREATE_DATE" TIMESTAMP (0) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFY_DATE" TIMESTAMP (0), 
	"UPDATE_PASS_DATE" TIMESTAMP (0), 
	"EXPIRATION_DATE" TIMESTAMP (0), 
	"METADATA" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("METADATA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table USER_SYS_ROLE_MAP
--------------------------------------------------------

  CREATE TABLE "DEMO_CA"."USER_SYS_ROLE_MAP" 
   (	"USER_SYS_ID" NUMBER(19,0), 
	"ROLE_ID" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into DEMO_CA.CERT
SET DEFINE OFF;
Insert into DEMO_CA.CERT (ID,SIGNER_ID,SERIAL,NAME,DN,UID_CERT,ISSUER,ISSUER_ID,OCSP_ID,VALIDFR,VALIDTO,KEYLENGTH,DESCRIPTION,BASE64,ALIAS,STATUS,CREATE_DATE,MODIFY_DATE,STATUS_CERT) values (261,201,'5404fffeb7033fb316d672201b7fe161','LY','CN=LY, UID=CMND:012770295','CMND:012770295','CN=Viettel-CA, O=Viettel Group, L=Hà Nội, C=VN',61,41,to_timestamp('01-DEC-19 01.23.27.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('30-NOV-20 01.23.27.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),1024,null,'-----BEGIN CERTIFICATE-----
MIID0DCCArigAwIBAgIQVAT//rcDP7MW1nIgG3/hYTANBgkqhkiG9w0BAQUFADBO
MQswCQYDVQQGEwJWTjESMBAGA1UEBwwJSMOgIE7hu5lpMRYwFAYDVQQKEw1WaWV0
dGVsIEdyb3VwMRMwEQYDVQQDEwpWaWV0dGVsLUNBMB4XDTE5MTEzMDE4MjMyN1oX
DTIwMTEyOTE4MjMyN1owLTEeMBwGCgmSJomT8ixkAQEMDkNNTkQ6MDEyNzcwMjk1
MQswCQYDVQQDDAJMWTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEA5117gwl1
kwRK8ojeNT83uDnWztYbyv96A7uJ9+o1mv5mPyxwSG9kA01yUT/MglVh12tpAeUS
u0JVS6pZIknpE8yX4ywj379LrZXCGgq5gWSoIbQ2Lh/8Suk0B/UXuevCD/+voZbU
CsYfSgY3paodyKiKV6blv/8KfOyUmEZz7L0CAwEAAaOCAU0wggFJMDUGCCsGAQUF
BwEBBCkwJzAlBggrBgEFBQcwAYYZaHR0cDovL29jc3AudmlldHRlbC1jYS52bjAd
BgNVHQ4EFgQUz2mY/3qftGZyD7+NljPisbIqE+QwDAYDVR0TAQH/BAIwADAfBgNV
HSMEGDAWgBT+y0EU6V2n2TIN5LIIXPFc7LaytTCBkgYDVR0fBIGKMIGHMIGEoC6g
LIYqaHR0cDovL2NybC52aWV0dGVsLWNhLnZuL1ZpZXR0ZWwtQ0EtdjMuY3JsolKk
UDBOMRMwEQYDVQQDDApWaWV0dGVsLUNBMRYwFAYDVQQKDA1WaWV0dGVsIEdyb3Vw
MRIwEAYDVQQHDAlIw6AgTuG7mWkxCzAJBgNVBAYTAlZOMA4GA1UdDwEB/wQEAwIF
4DAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwQwDQYJKoZIhvcNAQEFBQAD
ggEBALyozaxQjmB1Gc6GyByUbBZCVhAn+9tggSGiYCfImLICEuOBqO6HrEZ6Cdv3
hvNkzy8rRpOjIwjrRNnONwqA8+lMhpoguT0b8e+Zrbog30OryGsZONzb5Xl32e7x
OeZyG6OBNc9aTmj/pOde5hxHwPr9WDkHrrhS9Zi75WTlKF6vqcZVv644FBkdM9nw
z7Or4EyFSxEia+ORP4DntPtl3kL8IQKCT3Rcain7qkcWPaYQnea1+zMaWyQue6ou
nt8Bn8N/5HahAyptWqF+41KuU08qTmNvbXKB03aIW4HQRmeWJeTIrdVKdIMCiKSP
R0EJ0Q6JNAclmPUFrys6DFiVZrQ=
-----END CERTIFICATE-----
',null,1,to_timestamp('25-FEB-20 11.24.25.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.52.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),1);
REM INSERTING into DEMO_CA.CHANNEL
SET DEFINE OFF;
Insert into DEMO_CA.CHANNEL (ID,CHANNEL_CODE,STATUS,CREATE_DATE,MODIFY_DATE) values (61,'SME',1,to_timestamp('25-FEB-20 11.24.19.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.19.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
REM INSERTING into DEMO_CA.CUSTOMER
SET DEFINE OFF;
Insert into DEMO_CA.CUSTOMER (ID,CIF,STATUS,CREATE_DATE,MODIFY_DATE) values (61,'123456',1,to_timestamp('25-FEB-20 11.24.19.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.19.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
REM INSERTING into DEMO_CA.DOCUMENT
SET DEFINE OFF;
Insert into DEMO_CA.DOCUMENT (ID,TRANS_ID,TYPE,FOLDER_SAVE,SIZE_DOC,STATUS,CREATE_DATE,MODIFY_DATE,NAME_ORI,NAME_SAVE,ERROR_CODE_ID) values (361,684,1,'G:\Viettel-CA-IBM-3\SOURCE_VIETTEL_CA_XAC_THUC_CKS_VPB\DigitalVerifyServerWs\build\web\temp\1b4c9957-c10b-4225-baf6-fa6d670ac5e5.xml',16663,1,to_timestamp('25-FEB-20 11.24.25.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.25.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'123123123','1b4c9957-c10b-4225-baf6-fa6d670ac5e5',null);
Insert into DEMO_CA.DOCUMENT (ID,TRANS_ID,TYPE,FOLDER_SAVE,SIZE_DOC,STATUS,CREATE_DATE,MODIFY_DATE,NAME_ORI,NAME_SAVE,ERROR_CODE_ID) values (362,684,1,'G:\Viettel-CA-IBM-3\SOURCE_VIETTEL_CA_XAC_THUC_CKS_VPB\DigitalVerifyServerWs\build\web\temp\9846754c-69f6-467f-b635-72f341008e30.xml',16663,1,to_timestamp('25-FEB-20 11.24.25.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.25.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'123123123','9846754c-69f6-467f-b635-72f341008e30',null);
Insert into DEMO_CA.DOCUMENT (ID,TRANS_ID,TYPE,FOLDER_SAVE,SIZE_DOC,STATUS,CREATE_DATE,MODIFY_DATE,NAME_ORI,NAME_SAVE,ERROR_CODE_ID) values (363,684,1,'G:\Viettel-CA-IBM-3\SOURCE_VIETTEL_CA_XAC_THUC_CKS_VPB\DigitalVerifyServerWs\build\web\temp\72b22d1a-3b5a-4160-9dcc-554f34d4c42a.xml',16663,1,to_timestamp('25-FEB-20 11.24.25.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.25.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'123123123','72b22d1a-3b5a-4160-9dcc-554f34d4c42a',null);
REM INSERTING into DEMO_CA.ERROR_CODE
SET DEFINE OFF;
REM INSERTING into DEMO_CA.FUNCTION
SET DEFINE OFF;
REM INSERTING into DEMO_CA.OBJECT
SET DEFINE OFF;
REM INSERTING into DEMO_CA.OCSP
SET DEFINE OFF;
Insert into DEMO_CA.OCSP (ID,URL,DESCRIPTION,HAS_CONNECT,STATUS,CREATER_ID,CREATE_DATE,MODIFY_DATE) values (41,'http://ocsp.viettel-ca.vn',null,'Y',4,null,to_timestamp('25-FEB-20 11.24.23.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.24.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
REM INSERTING into DEMO_CA.ROLE
SET DEFINE OFF;
REM INSERTING into DEMO_CA.ROLE_FUNCTION_MAP
SET DEFINE OFF;
REM INSERTING into DEMO_CA.SERVER
SET DEFINE OFF;
Insert into DEMO_CA.SERVER (ID,NAME,IP,DESCRIPTION,STATUS,CREATE_DATE,MODIFY_DATE) values (1,'127.0.0.1','127.0.0.1',null,1,null,null);
Insert into DEMO_CA.SERVER (ID,NAME,IP,DESCRIPTION,STATUS,CREATE_DATE,MODIFY_DATE) values (41,'10.61.186.113','10.61.186.113',null,1,to_timestamp('17-FEB-20 08.52.27.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null);
Insert into DEMO_CA.SERVER (ID,NAME,IP,DESCRIPTION,STATUS,CREATE_DATE,MODIFY_DATE) values (21,'10.61.184.44','10.61.184.44',null,1,to_timestamp('12-FEB-20 05.29.04.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null);
REM INSERTING into DEMO_CA.SIGNATURE
SET DEFINE OFF;
Insert into DEMO_CA.SIGNATURE (ID,DOCUMENT_ID,CERT_ID,TYPE,STATUS,CREATE_DATE,MODIFY_DATE,SIGN_DATE,ERROR_CODE_ID) values (463,362,261,1,1,to_timestamp('25-FEB-20 11.24.25.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.25.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,null);
Insert into DEMO_CA.SIGNATURE (ID,DOCUMENT_ID,CERT_ID,TYPE,STATUS,CREATE_DATE,MODIFY_DATE,SIGN_DATE,ERROR_CODE_ID) values (464,362,261,1,1,to_timestamp('25-FEB-20 11.24.25.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.25.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,null);
Insert into DEMO_CA.SIGNATURE (ID,DOCUMENT_ID,CERT_ID,TYPE,STATUS,CREATE_DATE,MODIFY_DATE,SIGN_DATE,ERROR_CODE_ID) values (465,363,261,1,1,to_timestamp('25-FEB-20 11.24.25.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.25.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,null);
Insert into DEMO_CA.SIGNATURE (ID,DOCUMENT_ID,CERT_ID,TYPE,STATUS,CREATE_DATE,MODIFY_DATE,SIGN_DATE,ERROR_CODE_ID) values (466,363,261,1,1,to_timestamp('25-FEB-20 11.24.25.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.25.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,null);
Insert into DEMO_CA.SIGNATURE (ID,DOCUMENT_ID,CERT_ID,TYPE,STATUS,CREATE_DATE,MODIFY_DATE,SIGN_DATE,ERROR_CODE_ID) values (461,361,261,1,1,to_timestamp('25-FEB-20 11.24.25.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.25.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,null);
Insert into DEMO_CA.SIGNATURE (ID,DOCUMENT_ID,CERT_ID,TYPE,STATUS,CREATE_DATE,MODIFY_DATE,SIGN_DATE,ERROR_CODE_ID) values (462,361,261,1,1,to_timestamp('25-FEB-20 11.24.25.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.25.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null,null);
REM INSERTING into DEMO_CA.SIGNER
SET DEFINE OFF;
Insert into DEMO_CA.SIGNER (ID,CUSTOMER_ID,USERNAME,STATUS,CREATE_DATE,MODIFY_DATE,CHANNEL_ID) values (201,61,'kh_01',1,to_timestamp('25-FEB-20 11.24.24.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.52.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),61);
REM INSERTING into DEMO_CA.TRANS
SET DEFINE OFF;
Insert into DEMO_CA.TRANS (ID,TRANS_REF_ID,TRANS_REF_TYPE,SIGNER_ID,TYPE_ACTION,TYPE_HAS_SIGNATURE,STATUS,CREATE_DATE,MODIFY_DATE,SERVER_ID,CERT_ID,ERROR_CODE_ID) values (687,null,10,null,10,'N',1,to_timestamp('25-FEB-20 11.24.55.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.55.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),1,null,null);
Insert into DEMO_CA.TRANS (ID,TRANS_REF_ID,TRANS_REF_TYPE,SIGNER_ID,TYPE_ACTION,TYPE_HAS_SIGNATURE,STATUS,CREATE_DATE,MODIFY_DATE,SERVER_ID,CERT_ID,ERROR_CODE_ID) values (688,null,11,null,11,'N',1,to_timestamp('25-FEB-20 11.31.09.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.31.09.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),1,null,null);
Insert into DEMO_CA.TRANS (ID,TRANS_REF_ID,TRANS_REF_TYPE,SIGNER_ID,TYPE_ACTION,TYPE_HAS_SIGNATURE,STATUS,CREATE_DATE,MODIFY_DATE,SERVER_ID,CERT_ID,ERROR_CODE_ID) values (689,null,10,null,10,'N',1,to_timestamp('25-FEB-20 11.31.14.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.31.14.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),1,null,null);
Insert into DEMO_CA.TRANS (ID,TRANS_REF_ID,TRANS_REF_TYPE,SIGNER_ID,TYPE_ACTION,TYPE_HAS_SIGNATURE,STATUS,CREATE_DATE,MODIFY_DATE,SERVER_ID,CERT_ID,ERROR_CODE_ID) values (685,null,10,null,10,'N',1,to_timestamp('25-FEB-20 11.24.43.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.43.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),1,null,null);
Insert into DEMO_CA.TRANS (ID,TRANS_REF_ID,TRANS_REF_TYPE,SIGNER_ID,TYPE_ACTION,TYPE_HAS_SIGNATURE,STATUS,CREATE_DATE,MODIFY_DATE,SERVER_ID,CERT_ID,ERROR_CODE_ID) values (686,'123456sdf',2,null,1,'N',1,to_timestamp('25-FEB-20 11.24.52.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.52.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),1,null,null);
Insert into DEMO_CA.TRANS (ID,TRANS_REF_ID,TRANS_REF_TYPE,SIGNER_ID,TYPE_ACTION,TYPE_HAS_SIGNATURE,STATUS,CREATE_DATE,MODIFY_DATE,SERVER_ID,CERT_ID,ERROR_CODE_ID) values (683,null,11,null,11,'N',1,to_timestamp('25-FEB-20 11.24.03.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.03.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),1,null,null);
Insert into DEMO_CA.TRANS (ID,TRANS_REF_ID,TRANS_REF_TYPE,SIGNER_ID,TYPE_ACTION,TYPE_HAS_SIGNATURE,STATUS,CREATE_DATE,MODIFY_DATE,SERVER_ID,CERT_ID,ERROR_CODE_ID) values (684,'123456sdf',1,201,1,'Y',1,null,to_timestamp('25-FEB-20 11.24.25.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),1,261,null);
REM INSERTING into DEMO_CA.TRUSTED_CA
SET DEFINE OFF;
Insert into DEMO_CA.TRUSTED_CA (ID,SERIAL,NAME,DN,UID_CERT,ISSUER,ISSUER_ID,VALIDFR,VALIDTO,KEYLENGTH,DESCRIPTION,ALIAS,STATUS,CREATER_ID,CREATE_DATE,MODIFY_DATE) values (43,'610af15400000000000f','BkavCA','C=VN,L=Hanoi,O=Bkav Corporation,CN=BkavCA',null,'C=VN,L=Hanoi,O=Bkav Corporation,CN=BkavCA',null,to_timestamp('15-MAY-15 10.25.48.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('15-MAY-20 10.35.48.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),2048,null,null,1,null,to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into DEMO_CA.TRUSTED_CA (ID,SERIAL,NAME,DN,UID_CERT,ISSUER,ISSUER_ID,VALIDFR,VALIDTO,KEYLENGTH,DESCRIPTION,ALIAS,STATUS,CREATER_ID,CREATE_DATE,MODIFY_DATE) values (44,'6121a373000000000012','Viettel-CA','C=VN,L=Hà Nội,O=Viettel Group,CN=Viettel-CA',null,'C=VN,L=Hà Nội,O=Viettel Group,CN=Viettel-CA',null,to_timestamp('13-MAY-19 06.55.12.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('13-MAY-24 07.05.12.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),2048,null,null,1,null,to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into DEMO_CA.TRUSTED_CA (ID,SERIAL,NAME,DN,UID_CERT,ISSUER,ISSUER_ID,VALIDFR,VALIDTO,KEYLENGTH,DESCRIPTION,ALIAS,STATUS,CREATER_ID,CREATE_DATE,MODIFY_DATE) values (45,'61050dd2000000000004','VNPT Certification Authority','C=VN,O=VNPT Group,OU=VNPT-CA Trust Network,CN=VNPT Certification Authority',null,'C=VN,O=VNPT Group,OU=VNPT-CA Trust Network,CN=VNPT Certification Authority',null,to_timestamp('16-DEC-09 01.48.08.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('16-DEC-19 01.58.08.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),4096,null,null,1,null,to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into DEMO_CA.TRUSTED_CA (ID,SERIAL,NAME,DN,UID_CERT,ISSUER,ISSUER_ID,VALIDFR,VALIDTO,KEYLENGTH,DESCRIPTION,ALIAS,STATUS,CREATER_ID,CREATE_DATE,MODIFY_DATE) values (46,'61054d9a000000000012','FPT Certification Authority','C=VN,O=FPT Corporation,OU=FPT Information System,CN=FPT Certification Authority',null,'C=VN,O=FPT Corporation,OU=FPT Information System,CN=FPT Certification Authority',null,to_timestamp('21-OCT-15 10.34.57.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('21-OCT-20 10.44.57.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),2048,null,null,1,null,to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into DEMO_CA.TRUSTED_CA (ID,SERIAL,NAME,DN,UID_CERT,ISSUER,ISSUER_ID,VALIDFR,VALIDTO,KEYLENGTH,DESCRIPTION,ALIAS,STATUS,CREATER_ID,CREATE_DATE,MODIFY_DATE) values (47,'26636aedb6d347a3','EVNHN-CA','CN=EVNHN-CA,O=TCT DIEN LUC HA NOI,C=VN',null,'CN=EVNHN-CA,O=TCT DIEN LUC HA NOI,C=VN',null,to_timestamp('23-FEB-16 04.45.07.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('20-FEB-26 04.45.07.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),2048,null,null,1,null,to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into DEMO_CA.TRUSTED_CA (ID,SERIAL,NAME,DN,UID_CERT,ISSUER,ISSUER_ID,VALIDFR,VALIDTO,KEYLENGTH,DESCRIPTION,ALIAS,STATUS,CREATER_ID,CREATE_DATE,MODIFY_DATE) values (48,'6db5e836b5e05ab5','ManagementCA','CN=ManagementCA,O=EJBCA Sample,C=SE',null,'CN=ManagementCA,O=EJBCA Sample,C=SE',null,to_timestamp('09-JUN-15 06.14.37.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('06-JUN-25 06.14.37.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),2048,null,null,1,null,to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into DEMO_CA.TRUSTED_CA (ID,SERIAL,NAME,DN,UID_CERT,ISSUER,ISSUER_ID,VALIDFR,VALIDTO,KEYLENGTH,DESCRIPTION,ALIAS,STATUS,CREATER_ID,CREATE_DATE,MODIFY_DATE) values (49,'6107c476000000000009','FPT Certification Authority','C=VN,O=FPT Corporation,OU=FPT Information System,CN=FPT Certification Authority',null,'C=VN,O=FPT Corporation,OU=FPT Information System,CN=FPT Certification Authority',null,to_timestamp('08-NOV-10 09.21.27.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('08-NOV-15 09.31.27.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),4096,null,null,1,null,to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into DEMO_CA.TRUSTED_CA (ID,SERIAL,NAME,DN,UID_CERT,ISSUER,ISSUER_ID,VALIDFR,VALIDTO,KEYLENGTH,DESCRIPTION,ALIAS,STATUS,CREATER_ID,CREATE_DATE,MODIFY_DATE) values (41,'61073ca9000000000010','CA2','C=VN,O=NACENCOMM SCT,CN=CA2',null,'C=VN,O=NACENCOMM SCT,CN=CA2',null,to_timestamp('24-SEP-15 12.41.52.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('24-SEP-20 12.51.52.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),2048,null,null,1,null,to_timestamp('25-FEB-20 11.24.21.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.21.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into DEMO_CA.TRUSTED_CA (ID,SERIAL,NAME,DN,UID_CERT,ISSUER,ISSUER_ID,VALIDFR,VALIDTO,KEYLENGTH,DESCRIPTION,ALIAS,STATUS,CREATER_ID,CREATE_DATE,MODIFY_DATE) values (42,'61060a6300000000000a','CKCA','C=VN,O=CK Media and Technology JSC,OU=CKCA OrigSign,CN=CKCA',null,'C=VN,O=CK Media and Technology JSC,OU=CKCA OrigSign,CN=CKCA',null,to_timestamp('11-NOV-11 07.46.38.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('11-NOV-16 07.56.38.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),4096,null,null,1,null,to_timestamp('25-FEB-20 11.24.21.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.21.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into DEMO_CA.TRUSTED_CA (ID,SERIAL,NAME,DN,UID_CERT,ISSUER,ISSUER_ID,VALIDFR,VALIDTO,KEYLENGTH,DESCRIPTION,ALIAS,STATUS,CREATER_ID,CREATE_DATE,MODIFY_DATE) values (52,'610ef3e1000000000005','BkavCA','C=VN,L=Hanoi,O=Bkav Corporation,CN=BkavCA',null,'C=VN,L=Hanoi,O=Bkav Corporation,CN=BkavCA',null,to_timestamp('14-JUL-10 02.37.45.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('14-JUL-15 02.47.45.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),2048,null,null,1,null,to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into DEMO_CA.TRUSTED_CA (ID,SERIAL,NAME,DN,UID_CERT,ISSUER,ISSUER_ID,VALIDFR,VALIDTO,KEYLENGTH,DESCRIPTION,ALIAS,STATUS,CREATER_ID,CREATE_DATE,MODIFY_DATE) values (53,'1be4738a1f3ec08f479fa6cf35c59822','MIC National Root CA','C=VN,O=Ministry of Information and Communications,OU=National CA Center,CN=MIC National Root CA',null,'C=VN,O=Ministry of Information and Communications,OU=National CA Center,CN=MIC National Root CA',null,to_timestamp('16-MAY-08 08.12.49.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('16-MAY-40 08.20.32.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),2048,null,null,1,null,to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into DEMO_CA.TRUSTED_CA (ID,SERIAL,NAME,DN,UID_CERT,ISSUER,ISSUER_ID,VALIDFR,VALIDTO,KEYLENGTH,DESCRIPTION,ALIAS,STATUS,CREATER_ID,CREATE_DATE,MODIFY_DATE) values (54,'61095a3900000000000d','NEWTEL-CA','C=VN,O=CÔNG TY CỔ PHẦN VIỄN THÔNG NEW-TELECOM,CN=NEWTEL-CA',null,'C=VN,O=CÔNG TY CỔ PHẦN VIỄN THÔNG NEW-TELECOM,CN=NEWTEL-CA',null,to_timestamp('22-NOV-13 10.17.52.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('22-NOV-18 10.27.52.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),2048,null,null,1,null,to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into DEMO_CA.TRUSTED_CA (ID,SERIAL,NAME,DN,UID_CERT,ISSUER,ISSUER_ID,VALIDFR,VALIDTO,KEYLENGTH,DESCRIPTION,ALIAS,STATUS,CREATER_ID,CREATE_DATE,MODIFY_DATE) values (55,'6105af33000000000007','Viettel-CA','C=VN,O=Viettel Group,CN=Viettel-CA',null,'C=VN,O=Viettel Group,CN=Viettel-CA',null,to_timestamp('20-OCT-10 02.17.01.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('20-OCT-15 02.27.01.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),2048,null,null,1,null,to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into DEMO_CA.TRUSTED_CA (ID,SERIAL,NAME,DN,UID_CERT,ISSUER,ISSUER_ID,VALIDFR,VALIDTO,KEYLENGTH,DESCRIPTION,ALIAS,STATUS,CREATER_ID,CREATE_DATE,MODIFY_DATE) values (56,'610b3821000000000008','CA2','C=VN,O=NACENCOMM SCT,CN=CA2',null,'C=VN,O=NACENCOMM SCT,CN=CA2',null,to_timestamp('21-OCT-10 03.25.10.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('21-OCT-15 03.35.10.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),2048,null,null,1,null,to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into DEMO_CA.TRUSTED_CA (ID,SERIAL,NAME,DN,UID_CERT,ISSUER,ISSUER_ID,VALIDFR,VALIDTO,KEYLENGTH,DESCRIPTION,ALIAS,STATUS,CREATER_ID,CREATE_DATE,MODIFY_DATE) values (57,'615863fd00000000000b','SAFE-CA','C=VN,O=\ SAFE-CA Joint Stock Company,OU=SAFE-CA,CN=SAFE-CA',null,'C=VN,O=\ SAFE-CA Joint Stock Company,OU=SAFE-CA,CN=SAFE-CA',null,to_timestamp('02-OCT-12 03.35.39.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('02-OCT-17 03.45.39.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),2048,null,null,1,null,to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into DEMO_CA.TRUSTED_CA (ID,SERIAL,NAME,DN,UID_CERT,ISSUER,ISSUER_ID,VALIDFR,VALIDTO,KEYLENGTH,DESCRIPTION,ALIAS,STATUS,CREATER_ID,CREATE_DATE,MODIFY_DATE) values (58,'6121a373000000000012','Viettel-CA','C=VN,L=Hà Nội,O=Viettel Group,CN=Viettel-CA',null,'C=VN,L=Hà Nội,O=Viettel Group,CN=Viettel-CA',null,to_timestamp('13-MAY-19 06.55.12.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('13-MAY-24 07.05.12.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),2048,null,null,4,null,null,to_timestamp('25-FEB-20 11.24.23.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into DEMO_CA.TRUSTED_CA (ID,SERIAL,NAME,DN,UID_CERT,ISSUER,ISSUER_ID,VALIDFR,VALIDTO,KEYLENGTH,DESCRIPTION,ALIAS,STATUS,CREATER_ID,CREATE_DATE,MODIFY_DATE) values (59,'6121a373000000000012','Viettel-CA','C=VN,L=Hà Nội,O=Viettel Group,CN=Viettel-CA',null,'C=VN,L=Hà Nội,O=Viettel Group,CN=Viettel-CA',null,to_timestamp('13-MAY-19 06.55.12.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('13-MAY-24 07.05.12.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),2048,null,null,4,null,null,to_timestamp('25-FEB-20 11.24.23.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into DEMO_CA.TRUSTED_CA (ID,SERIAL,NAME,DN,UID_CERT,ISSUER,ISSUER_ID,VALIDFR,VALIDTO,KEYLENGTH,DESCRIPTION,ALIAS,STATUS,CREATER_ID,CREATE_DATE,MODIFY_DATE) values (60,'6121a373000000000012','Viettel-CA','C=VN,L=Hà Nội,O=Viettel Group,CN=Viettel-CA',null,'C=VN,L=Hà Nội,O=Viettel Group,CN=Viettel-CA',null,to_timestamp('13-MAY-19 06.55.12.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('13-MAY-24 07.05.12.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),2048,null,null,4,null,null,to_timestamp('25-FEB-20 11.24.24.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into DEMO_CA.TRUSTED_CA (ID,SERIAL,NAME,DN,UID_CERT,ISSUER,ISSUER_ID,VALIDFR,VALIDTO,KEYLENGTH,DESCRIPTION,ALIAS,STATUS,CREATER_ID,CREATE_DATE,MODIFY_DATE) values (61,'6121a373000000000012','Viettel-CA','C=VN,L=Hà Nội,O=Viettel Group,CN=Viettel-CA',null,'C=VN,L=Hà Nội,O=Viettel Group,CN=Viettel-CA',null,to_timestamp('13-MAY-19 06.55.12.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('13-MAY-24 07.05.12.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),2048,null,null,4,null,null,to_timestamp('25-FEB-20 11.24.24.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into DEMO_CA.TRUSTED_CA (ID,SERIAL,NAME,DN,UID_CERT,ISSUER,ISSUER_ID,VALIDFR,VALIDTO,KEYLENGTH,DESCRIPTION,ALIAS,STATUS,CREATER_ID,CREATE_DATE,MODIFY_DATE) values (62,'6121a373000000000012','Viettel-CA','C=VN,L=Hà Nội,O=Viettel Group,CN=Viettel-CA',null,'C=VN,L=Hà Nội,O=Viettel Group,CN=Viettel-CA',null,to_timestamp('13-MAY-19 06.55.12.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('13-MAY-24 07.05.12.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),2048,null,null,4,null,null,to_timestamp('25-FEB-20 11.24.24.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into DEMO_CA.TRUSTED_CA (ID,SERIAL,NAME,DN,UID_CERT,ISSUER,ISSUER_ID,VALIDFR,VALIDTO,KEYLENGTH,DESCRIPTION,ALIAS,STATUS,CREATER_ID,CREATE_DATE,MODIFY_DATE) values (63,'6121a373000000000012','Viettel-CA','C=VN,L=Hà Nội,O=Viettel Group,CN=Viettel-CA',null,'C=VN,L=Hà Nội,O=Viettel Group,CN=Viettel-CA',null,to_timestamp('13-MAY-19 06.55.12.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('13-MAY-24 07.05.12.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),2048,null,null,4,null,null,to_timestamp('25-FEB-20 11.24.24.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into DEMO_CA.TRUSTED_CA (ID,SERIAL,NAME,DN,UID_CERT,ISSUER,ISSUER_ID,VALIDFR,VALIDTO,KEYLENGTH,DESCRIPTION,ALIAS,STATUS,CREATER_ID,CREATE_DATE,MODIFY_DATE) values (50,'6106e12b00000000000c','SmartSign','C=VN,O=Cong ty co phan chu ky so VI NA,CN=SmartSign',null,'C=VN,O=Cong ty co phan chu ky so VI NA,CN=SmartSign',null,to_timestamp('26-NOV-12 02.52.36.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('26-NOV-17 03.02.36.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),2048,null,null,1,null,to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into DEMO_CA.TRUSTED_CA (ID,SERIAL,NAME,DN,UID_CERT,ISSUER,ISSUER_ID,VALIDFR,VALIDTO,KEYLENGTH,DESCRIPTION,ALIAS,STATUS,CREATER_ID,CREATE_DATE,MODIFY_DATE) values (51,'610e0de6000000000011','Viettel-CA','C=VN,O=Viettel Group,CN=Viettel-CA',null,'C=VN,O=Viettel Group,CN=Viettel-CA',null,to_timestamp('02-OCT-15 09.32.20.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('02-OCT-20 09.42.20.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),2048,null,null,1,null,to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('25-FEB-20 11.24.22.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
REM INSERTING into DEMO_CA.TRUSTED_CA_OCSP_MAP
SET DEFINE OFF;
Insert into DEMO_CA.TRUSTED_CA_OCSP_MAP (TRUSTED_CA_ID,OCSP_ID) values (63,41);
REM INSERTING into DEMO_CA.USER_SYS
SET DEFINE OFF;
REM INSERTING into DEMO_CA.USER_SYS_ROLE_MAP
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index OCSP_URL_INDEX
--------------------------------------------------------

  CREATE INDEX "DEMO_CA"."OCSP_URL_INDEX" ON "DEMO_CA"."OCSP" ("URL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMO_CA" ;
--------------------------------------------------------
--  DDL for Index SIGNER_CHANNEL_ID_INDEX
--------------------------------------------------------

  CREATE INDEX "DEMO_CA"."SIGNER_CHANNEL_ID_INDEX" ON "DEMO_CA"."SIGNER" ("CHANNEL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMO_CA" ;
--------------------------------------------------------
--  DDL for Index FUNCTION_OBJECT_ID_INDEX
--------------------------------------------------------

  CREATE INDEX "DEMO_CA"."FUNCTION_OBJECT_ID_INDEX" ON "DEMO_CA"."FUNCTION" ("OBJECT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DEMO_CA" ;
--------------------------------------------------------
--  DDL for Index SERVER_IP_INDEX
--------------------------------------------------------

  CREATE INDEX "DEMO_CA"."SERVER_IP_INDEX" ON "DEMO_CA"."SERVER" ("IP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMO_CA" ;
--------------------------------------------------------
--  DDL for Index SIGNER_CUSTOMER_ID_INDEX
--------------------------------------------------------

  CREATE INDEX "DEMO_CA"."SIGNER_CUSTOMER_ID_INDEX" ON "DEMO_CA"."SIGNER" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMO_CA" ;
--------------------------------------------------------
--  DDL for Index SIGNATURE_CREATE_DATE_INDEX
--------------------------------------------------------

  CREATE INDEX "DEMO_CA"."SIGNATURE_CREATE_DATE_INDEX" ON "DEMO_CA"."SIGNATURE" ("CREATE_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMO_CA" ;
--------------------------------------------------------
--  DDL for Index TRANS_SIGNER_ID_INDEX
--------------------------------------------------------

  CREATE INDEX "DEMO_CA"."TRANS_SIGNER_ID_INDEX" ON "DEMO_CA"."TRANS" ("SIGNER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMO_CA" ;
--------------------------------------------------------
--  DDL for Index CHANNEL_CODE_INDEX
--------------------------------------------------------

  CREATE INDEX "DEMO_CA"."CHANNEL_CODE_INDEX" ON "DEMO_CA"."CHANNEL" ("CHANNEL_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMO_CA" ;
--------------------------------------------------------
--  DDL for Index DOCUMENT_TRANS_ID_INDEX
--------------------------------------------------------

  CREATE INDEX "DEMO_CA"."DOCUMENT_TRANS_ID_INDEX" ON "DEMO_CA"."DOCUMENT" ("TRANS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMO_CA" ;
--------------------------------------------------------
--  DDL for Index SIGNATURE_DOCUMENT_ID_INDEX
--------------------------------------------------------

  CREATE INDEX "DEMO_CA"."SIGNATURE_DOCUMENT_ID_INDEX" ON "DEMO_CA"."SIGNATURE" ("DOCUMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMO_CA" ;
--------------------------------------------------------
--  DDL for Index TRUSTED_VALIDTO_INDEX
--------------------------------------------------------

  CREATE INDEX "DEMO_CA"."TRUSTED_VALIDTO_INDEX" ON "DEMO_CA"."TRUSTED_CA" ("VALIDTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMO_CA" ;
--------------------------------------------------------
--  DDL for Index USER_SYS_USERNAME_INDEX
--------------------------------------------------------

  CREATE INDEX "DEMO_CA"."USER_SYS_USERNAME_INDEX" ON "DEMO_CA"."USER_SYS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DEMO_CA" ;
--------------------------------------------------------
--  DDL for Index SIGNER_CREATE_DATE_INDEX
--------------------------------------------------------

  CREATE INDEX "DEMO_CA"."SIGNER_CREATE_DATE_INDEX" ON "DEMO_CA"."SIGNER" ("CREATE_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMO_CA" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_CIF_INDEX
--------------------------------------------------------

  CREATE INDEX "DEMO_CA"."CUSTOMER_CIF_INDEX" ON "DEMO_CA"."CUSTOMER" ("CIF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMO_CA" ;
--------------------------------------------------------
--  DDL for Index CERT_VALIDFR_INDEX
--------------------------------------------------------

  CREATE INDEX "DEMO_CA"."CERT_VALIDFR_INDEX" ON "DEMO_CA"."CERT" ("VALIDFR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMO_CA" ;
--------------------------------------------------------
--  DDL for Index TRANS_SERVER_ID_INDEX
--------------------------------------------------------

  CREATE INDEX "DEMO_CA"."TRANS_SERVER_ID_INDEX" ON "DEMO_CA"."TRANS" ("SERVER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMO_CA" ;
--------------------------------------------------------
--  DDL for Index CERT_SERIAL_INDEX
--------------------------------------------------------

  CREATE INDEX "DEMO_CA"."CERT_SERIAL_INDEX" ON "DEMO_CA"."CERT" ("SERIAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMO_CA" ;
--------------------------------------------------------
--  DDL for Index TRANS_CREATE_DATE_INDEX
--------------------------------------------------------

  CREATE INDEX "DEMO_CA"."TRANS_CREATE_DATE_INDEX" ON "DEMO_CA"."TRANS" ("CREATE_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMO_CA" ;
--------------------------------------------------------
--  DDL for Index CERT_VALIDTO_INDEX
--------------------------------------------------------

  CREATE INDEX "DEMO_CA"."CERT_VALIDTO_INDEX" ON "DEMO_CA"."CERT" ("VALIDTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMO_CA" ;
--------------------------------------------------------
--  DDL for Index TRUSTED_VALIDFR_INDEX
--------------------------------------------------------

  CREATE INDEX "DEMO_CA"."TRUSTED_VALIDFR_INDEX" ON "DEMO_CA"."TRUSTED_CA" ("VALIDFR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMO_CA" ;
--------------------------------------------------------
--  DDL for Index TRANS_CERT_ID_INDEX
--------------------------------------------------------

  CREATE INDEX "DEMO_CA"."TRANS_CERT_ID_INDEX" ON "DEMO_CA"."TRANS" ("CERT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMO_CA" ;
--------------------------------------------------------
--  DDL for Index SIGNATURE_CERT_ID_INDEX
--------------------------------------------------------

  CREATE INDEX "DEMO_CA"."SIGNATURE_CERT_ID_INDEX" ON "DEMO_CA"."SIGNATURE" ("CERT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMO_CA" ;
--------------------------------------------------------
--  DDL for Index TRANS_TRANS_REF_ID_INDEX
--------------------------------------------------------

  CREATE INDEX "DEMO_CA"."TRANS_TRANS_REF_ID_INDEX" ON "DEMO_CA"."TRANS" ("TRANS_REF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMO_CA" ;
--------------------------------------------------------
--  DDL for Index OBJECT_HREF_INDEX
--------------------------------------------------------

  CREATE INDEX "DEMO_CA"."OBJECT_HREF_INDEX" ON "DEMO_CA"."OBJECT" ("HREF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "DEMO_CA" ;
--------------------------------------------------------
--  DDL for Index SIGNER_USERNAME_INDEX
--------------------------------------------------------

  CREATE INDEX "DEMO_CA"."SIGNER_USERNAME_INDEX" ON "DEMO_CA"."SIGNER" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEMO_CA" ;
--------------------------------------------------------
--  DDL for Trigger CERT_CREATE_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."CERT_CREATE_DATE_TR" 
 BEFORE INSERT ON CERT 
 FOR EACH ROW
BEGIN
 :new.CREATE_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."CERT_CREATE_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CERT_MODIFY_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."CERT_MODIFY_DATE_TR" 
 BEFORE INSERT OR UPDATE ON CERT 
 FOR EACH ROW
BEGIN
 :new.MODIFY_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."CERT_MODIFY_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CERT_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."CERT_SEQ_TR" 
 BEFORE INSERT ON CERT FOR EACH ROW
    WHEN (NEW.ID IS NULL) BEGIN
 SELECT CERT_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "DEMO_CA"."CERT_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CHANNEL_CREATE_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."CHANNEL_CREATE_DATE_TR" 
 BEFORE INSERT ON CHANNEL 
 FOR EACH ROW
BEGIN
 :new.CREATE_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."CHANNEL_CREATE_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CHANNEL_MODIFY_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."CHANNEL_MODIFY_DATE_TR" 
 BEFORE INSERT OR UPDATE ON CHANNEL 
 FOR EACH ROW
BEGIN
 :new.MODIFY_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."CHANNEL_MODIFY_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CHANNEL_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."CHANNEL_SEQ_TR" 
 BEFORE INSERT ON CHANNEL FOR EACH ROW
    WHEN (NEW.ID IS NULL) BEGIN
 SELECT CHANNEL_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "DEMO_CA"."CHANNEL_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CUSTOMER_CREATE_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."CUSTOMER_CREATE_DATE_TR" 
 BEFORE INSERT ON CUSTOMER 
 FOR EACH ROW
BEGIN
 :new.CREATE_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."CUSTOMER_CREATE_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CUSTOMER_MODIFY_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."CUSTOMER_MODIFY_DATE_TR" 
 BEFORE INSERT OR UPDATE ON CUSTOMER 
 FOR EACH ROW
BEGIN
 :new.MODIFY_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."CUSTOMER_MODIFY_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CUSTOMER_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."CUSTOMER_SEQ_TR" 
 BEFORE INSERT ON CUSTOMER FOR EACH ROW
    WHEN (NEW.ID IS NULL) BEGIN
 SELECT CUSTOMER_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "DEMO_CA"."CUSTOMER_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DOCUMENT_CREATE_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."DOCUMENT_CREATE_DATE_TR" 
 BEFORE INSERT ON DOCUMENT 
 FOR EACH ROW
BEGIN
 :new.CREATE_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."DOCUMENT_CREATE_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DOCUMENT_MODIFY_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."DOCUMENT_MODIFY_DATE_TR" 
 BEFORE INSERT OR UPDATE ON DOCUMENT 
 FOR EACH ROW
BEGIN
 :new.MODIFY_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."DOCUMENT_MODIFY_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DOCUMENT_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."DOCUMENT_SEQ_TR" 
 BEFORE INSERT ON DOCUMENT FOR EACH ROW
    WHEN (NEW.ID IS NULL) BEGIN
 SELECT DOCUMENT_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "DEMO_CA"."DOCUMENT_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ERROR_CODE_CREATE_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."ERROR_CODE_CREATE_DATE_TR" 
 BEFORE INSERT ON ERROR_CODE 
 FOR EACH ROW
BEGIN
 :new.CREATE_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."ERROR_CODE_CREATE_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ERROR_CODE_MODIFY_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."ERROR_CODE_MODIFY_DATE_TR" 
 BEFORE INSERT OR UPDATE ON ERROR_CODE 
 FOR EACH ROW
BEGIN
 :new.MODIFY_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."ERROR_CODE_MODIFY_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ERROR_CODE_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."ERROR_CODE_SEQ_TR" 
 BEFORE INSERT ON ERROR_CODE FOR EACH ROW
    WHEN (NEW.ID IS NULL) BEGIN
 SELECT ERROR_CODE_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "DEMO_CA"."ERROR_CODE_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FUNCTION_CREATE_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."FUNCTION_CREATE_DATE_TR" 
 BEFORE INSERT ON FUNCTION 
 FOR EACH ROW
BEGIN
 :new.CREATE_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."FUNCTION_CREATE_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FUNCTION_MODIFY_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."FUNCTION_MODIFY_DATE_TR" 
 BEFORE INSERT OR UPDATE ON FUNCTION 
 FOR EACH ROW
BEGIN
 :new.MODIFY_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."FUNCTION_MODIFY_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FUNCTION_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."FUNCTION_SEQ_TR" 
 BEFORE INSERT ON FUNCTION FOR EACH ROW
    WHEN (NEW.ID IS NULL) BEGIN
 SELECT FUNCTION_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "DEMO_CA"."FUNCTION_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger OBJECT_CREATE_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."OBJECT_CREATE_DATE_TR" 
 BEFORE INSERT ON OBJECT 
 FOR EACH ROW
BEGIN
 :new.CREATE_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."OBJECT_CREATE_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger OBJECT_MODIFY_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."OBJECT_MODIFY_DATE_TR" 
 BEFORE INSERT OR UPDATE ON OBJECT 
 FOR EACH ROW
BEGIN
 :new.MODIFY_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."OBJECT_MODIFY_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger OBJECT_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."OBJECT_SEQ_TR" 
 BEFORE INSERT ON OBJECT FOR EACH ROW
    WHEN (NEW.ID IS NULL) BEGIN
 SELECT OBJECT_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "DEMO_CA"."OBJECT_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger OCSP_CREATE_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."OCSP_CREATE_DATE_TR" 
 BEFORE INSERT ON OCSP 
 FOR EACH ROW
BEGIN
 :new.CREATE_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."OCSP_CREATE_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger OCSP_MODIFY_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."OCSP_MODIFY_DATE_TR" 
 BEFORE INSERT OR UPDATE ON OCSP 
 FOR EACH ROW
BEGIN
 :new.MODIFY_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."OCSP_MODIFY_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger OCSP_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."OCSP_SEQ_TR" 
 BEFORE INSERT ON OCSP FOR EACH ROW
    WHEN (NEW.ID IS NULL) BEGIN
 SELECT OCSP_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "DEMO_CA"."OCSP_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ROLE_CREATE_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."ROLE_CREATE_DATE_TR" 
 BEFORE INSERT ON ROLE 
 FOR EACH ROW
BEGIN
 :new.CREATE_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."ROLE_CREATE_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ROLE_MODIFY_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."ROLE_MODIFY_DATE_TR" 
 BEFORE INSERT OR UPDATE ON ROLE 
 FOR EACH ROW
BEGIN
 :new.MODIFY_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."ROLE_MODIFY_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ROLE_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."ROLE_SEQ_TR" 
 BEFORE INSERT ON ROLE FOR EACH ROW
    WHEN (NEW.ID IS NULL) BEGIN
 SELECT ROLE_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "DEMO_CA"."ROLE_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SERVER_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."SERVER_SEQ_TR" 
 BEFORE INSERT ON SERVER FOR EACH ROW
    WHEN (NEW.ID IS NULL) BEGIN
 SELECT SERVER_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "DEMO_CA"."SERVER_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SIGNATURE_CREATE_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."SIGNATURE_CREATE_DATE_TR" 
 BEFORE INSERT ON SIGNATURE 
 FOR EACH ROW
BEGIN
 :new.CREATE_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."SIGNATURE_CREATE_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SIGNATURE_MODIFY_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."SIGNATURE_MODIFY_DATE_TR" 
 BEFORE INSERT OR UPDATE ON SIGNATURE 
 FOR EACH ROW
BEGIN
 :new.MODIFY_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."SIGNATURE_MODIFY_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SIGNATURE_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."SIGNATURE_SEQ_TR" 
 BEFORE INSERT ON SIGNATURE FOR EACH ROW
    WHEN (NEW.ID IS NULL) BEGIN
 SELECT SIGNATURE_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "DEMO_CA"."SIGNATURE_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SIGNER_CREATE_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."SIGNER_CREATE_DATE_TR" 
 BEFORE INSERT ON SIGNER 
 FOR EACH ROW
BEGIN
 :new.CREATE_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."SIGNER_CREATE_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SIGNER_MODIFY_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."SIGNER_MODIFY_DATE_TR" 
 BEFORE INSERT OR UPDATE ON SIGNER 
 FOR EACH ROW
BEGIN
 :new.MODIFY_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."SIGNER_MODIFY_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SIGNER_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."SIGNER_SEQ_TR" 
 BEFORE INSERT ON SIGNER FOR EACH ROW
    WHEN (NEW.ID IS NULL) BEGIN
 SELECT SIGNER_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "DEMO_CA"."SIGNER_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRANS_CREATE_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."TRANS_CREATE_DATE_TR" 
 BEFORE INSERT ON TRANS 
 FOR EACH ROW
BEGIN
 :new.CREATE_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."TRANS_CREATE_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRANS_MODIFY_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."TRANS_MODIFY_DATE_TR" 
 BEFORE INSERT OR UPDATE ON TRANS 
 FOR EACH ROW
BEGIN
 :new.MODIFY_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."TRANS_MODIFY_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRANS_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."TRANS_SEQ_TR" 
 BEFORE INSERT ON TRANS FOR EACH ROW
    WHEN (NEW.ID IS NULL) BEGIN
 SELECT TRANS_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "DEMO_CA"."TRANS_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRUSTED_CA_CREATE_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."TRUSTED_CA_CREATE_DATE_TR" 
 BEFORE INSERT ON TRUSTED_CA 
 FOR EACH ROW
BEGIN
 :new.CREATE_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."TRUSTED_CA_CREATE_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRUSTED_CA_MODIFY_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."TRUSTED_CA_MODIFY_DATE_TR" 
 BEFORE INSERT OR UPDATE ON TRUSTED_CA 
 FOR EACH ROW
BEGIN
 :new.MODIFY_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."TRUSTED_CA_MODIFY_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRUSTED_CA_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."TRUSTED_CA_SEQ_TR" 
 BEFORE INSERT ON TRUSTED_CA FOR EACH ROW
    WHEN (NEW.ID IS NULL) BEGIN
 SELECT TRUSTED_CA_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "DEMO_CA"."TRUSTED_CA_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USER_SYS_CREATE_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."USER_SYS_CREATE_DATE_TR" 
 BEFORE INSERT ON USER_SYS 
 FOR EACH ROW
BEGIN
 :new.CREATE_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."USER_SYS_CREATE_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USER_SYS_MODIFY_DATE_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."USER_SYS_MODIFY_DATE_TR" 
 BEFORE INSERT OR UPDATE ON USER_SYS 
 FOR EACH ROW
BEGIN
 :new.MODIFY_DATE := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "DEMO_CA"."USER_SYS_MODIFY_DATE_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USER_SYS_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_CA"."USER_SYS_SEQ_TR" 
 BEFORE INSERT ON USER_SYS FOR EACH ROW
    WHEN (NEW.ID IS NULL) BEGIN
 SELECT USER_SYS_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/
ALTER TRIGGER "DEMO_CA"."USER_SYS_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table ERROR_CODE
--------------------------------------------------------

  ALTER TABLE "DEMO_CA"."ERROR_CODE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "DEMO_CA"."CUSTOMER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_SYS_ROLE_MAP
--------------------------------------------------------

  ALTER TABLE "DEMO_CA"."USER_SYS_ROLE_MAP" ADD PRIMARY KEY ("USER_SYS_ID", "ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLE_FUNCTION_MAP
--------------------------------------------------------

  ALTER TABLE "DEMO_CA"."ROLE_FUNCTION_MAP" ADD PRIMARY KEY ("ROLE_ID", "FUNCTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRUSTED_CA_OCSP_MAP
--------------------------------------------------------

  ALTER TABLE "DEMO_CA"."TRUSTED_CA_OCSP_MAP" ADD PRIMARY KEY ("TRUSTED_CA_ID", "OCSP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRANS
--------------------------------------------------------

  ALTER TABLE "DEMO_CA"."TRANS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CERT
--------------------------------------------------------

  ALTER TABLE "DEMO_CA"."CERT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_SYS
--------------------------------------------------------

  ALTER TABLE "DEMO_CA"."USER_SYS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CHANNEL
--------------------------------------------------------

  ALTER TABLE "DEMO_CA"."CHANNEL" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OCSP
--------------------------------------------------------

  ALTER TABLE "DEMO_CA"."OCSP" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FUNCTION
--------------------------------------------------------

  ALTER TABLE "DEMO_CA"."FUNCTION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OBJECT
--------------------------------------------------------

  ALTER TABLE "DEMO_CA"."OBJECT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DOCUMENT
--------------------------------------------------------

  ALTER TABLE "DEMO_CA"."DOCUMENT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SIGNER
--------------------------------------------------------

  ALTER TABLE "DEMO_CA"."SIGNER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRUSTED_CA
--------------------------------------------------------

  ALTER TABLE "DEMO_CA"."TRUSTED_CA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SIGNATURE
--------------------------------------------------------

  ALTER TABLE "DEMO_CA"."SIGNATURE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLE
--------------------------------------------------------

  ALTER TABLE "DEMO_CA"."ROLE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SERVER
--------------------------------------------------------

  ALTER TABLE "DEMO_CA"."SERVER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
